# Generated by Django 4.2.2 on 2023-07-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0002_alter_book_edition_alter_client_firstname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userid',
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default='apellido y nombre', max_length=20),
            preserve_default=False,
        ),
    ]
