# Generated by Django 4.2.2 on 2023-07-15 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0003_remove_user_userid_user_fullname'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcover', models.ImageField(blank=True, null=True, upload_to='bookcover_folder')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='initial.book')),
            ],
        ),
    ]
