# Generated by Django 4.2.2 on 2023-07-15 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0005_alter_bookextra_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookextra',
            name='book',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='initial.book'),
        ),
    ]
