# Generated by Django 4.2.2 on 2023-07-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0006_alter_bookextra_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bookcover',
            field=models.ImageField(blank=True, null=True, upload_to='bookcover_folder'),
        ),
        migrations.DeleteModel(
            name='BookExtra',
        ),
    ]
