# Generated by Django 4.2.2 on 2023-07-15 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0007_book_bookcover_delete_bookextra'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='createdbyuser',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='createdbyuser',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
