# Generated by Django 4.2.2 on 2023-07-16 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0008_book_createdbyuser_client_createdbyuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
