# Generated by Django 4.2.2 on 2023-07-16 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0009_client_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='observaciones',
            field=models.TextField(null=True),
        ),
    ]
