# Generated by Django 4.2.2 on 2023-07-16 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0010_book_descripcion_client_observaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='observaciones',
            new_name='comments',
        ),
    ]
