# Generated by Django 4.2.2 on 2023-07-18 00:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0011_rename_descripcion_book_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='comments',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
