# Generated by Django 4.2.2 on 2023-07-18 01:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0012_alter_client_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='description',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
