# Generated by Django 4.2.2 on 2023-07-18 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0013_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
