# Generated by Django 4.2.2 on 2023-07-24 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('initial', '0014_alter_client_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
