# Generated by Django 4.2.2 on 2023-08-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userinbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextra',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20, null=True),
        ),
    ]
